### ISSUE TITLE
Questions about the query ecall-args-isoutsideenclave

### ISSUE THREAD

**Issue by qinkunbao** [openenclave/openenclave-security#18]
Hi,

I tested the query `ecall-args-isoutsideenclave` with a simple example below.

enclave.c
```
void ecall_check_usercheck_error(int num, int *ret)
{
    if (ret == NULL) {
        return;
    }
    if (num % 2 == 0) {
        *ret = 0;
    }
    else {
        *ret = 1;
    }
}
```

edl
```
public void ecall_check_usercheck_error(int num, [user_check] int *ret);
```
Based on my understanding, the enclave code misses boundary check when accessing the pointer `ret` passed from the host. So it should be an error here. I built the example (modified from the hello world example) with Open Enclave 0.15.0. However, the query `ecall-args-isoutsideenclave` failed to detect such an error. I believe the above code is a minimal example of such errors. So I wonder what kinds of vulnerabilities can this query catch?

**Comment by mrragava** [comment]
ecall-args-isoutsideenclave query is to detect IsOutsodeEnclave check in ECALL entry point (__oe_handle_main) in OpenEnclaveSDK impl. 
It is modeled based on https://github.com/openenclave/openenclave-security/blob/5882f3a86e2a932077c4faa4dca7b71dbfeeda64/src/static/codeql/queries/cpp/openenclave/OpenEnclave.qll#L15.
You could modify this query to your ecalls by modelling the ECALL function patterns.

**Comment by qinkunbao** [comment]
Thanks. I did. I changed the name of the entry point. However, the query still cannot detect the error.

https://github.com/openenclave/openenclave-security/blob/5882f3a86e2a932077c4faa4dca7b71dbfeeda64/src/static/codeql/queries/cpp/openenclave/OpenEnclave.qll#L34

It looks like the query assumes the second parameter is an untrusted pointer from the host. However, the assumption doesn't hold for a general ECALL, right?

Besides, `__oe_handle_main` is the entry function for all other ECALLs. A proper data flow analysis should propagate the untrusted points to my ecall calls. I don't understand why I need to modify this query to my ecall's name.

**Comment by mrragava** [comment]
EnclaveEnterFunction is modeled based on the definition from https://github.com/openenclave/openenclave/blob/master/enclave/core/sgx/calls.c#L948. Taint sink int the query validates until the untrusted data is copied to enclave memory. https://github.com/openenclave/openenclave/blob/master/enclave/core/sgx/calls.c#L219. 
These queries are pertained to OE specific and not intended to work as a generic query for all enclave ECALLs.

**Comment by qinkunbao** [comment]
Thank you! Suppose I write an enclave application based on OE SDK, and the application has a user defined ecall with an unchecked pointer. The query `ecall-args-isoutsideenclave` is not designed to detect such an error, though the application is based on OE SDK. Is that correct?

**Comment by mrragava** [comment]
Yes that is correct, At the moment these queries are OE-SDK specific. I could see certainly see the benefits to extend or add more queries and libraries that OE-SDK client can make use of. This is something we could evolve with community involvement.

**Comment by qinkunbao** [comment]
Thanks!
